# Generated by Django 4.2 on 2023-04-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='all categories'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name=''),
        ),
    ]
