# Generated by Django 4.2 on 2023-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_categories_alter_blog_featured_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_media/'),
        ),
    ]
