# Generated by Django 4.2 on 2023-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_featured_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Published'), ('3', 'Pending')], default='Draft', max_length=15),
        ),
    ]
