# Generated by Django 4.2 on 2023-04-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
